### ISSUE TITLE
OSX binaries

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mwild1/luadbi#17]
```
Building OSX binaries is not easy. Does anyone have 32/64 bit Intel binaries 
ready for download (mysql, postgre, sqlite)?
```

Original issue reported on code.google.com by `patest...@gmail.com` on 24 Jan 2013 at 2:29

**Comment by mwild1** [comment]
As a Linux person I'm not in a position to provide OS X binaries, and luarocks may be a decent solution to building on OS X these days.
