### ISSUE TITLE
Sync source in repo and in LuaRocks

### ISSUE THREAD

**Issue by moteus** [mwild1/luadbi#32]
In LuaRocks version 0.5 drivers loaded as `dbd.<driver>` but in current repo they loaded like `dbd<driver>`

**Comment by sparked435** [comment]
This was me, when I built the original Luarocks modules some time ago. It was partially taste but also it made using the built in Luarocks build system easier.

I would have synced it sooner but doing so will break the Visual Studio project and I have no means of supporting Windows at this time.

**Comment by fliiiix** [comment]
Is there any progress? Since https://luarocks.org/modules/luarocks/luadbi still points to google code

**Comment by moteus** [comment]
@sparked435 So you do no decide change source on this repo to use `dbd.<driver>` like in version 0.5 and use `dbd<driver>` notation.
I think because current release on LuaRocks uses such code it worth also change it in currect repo.

**Comment by sparked435** [comment]
This issue is still open because I have not yet made the change. :)

I'm looking into seeing if this will break anything on Windows, which is difficult, as I don't have access to any Windows system for development.

**Comment by sparked435** [comment]
Fixed in commit bdaf2445e1a596a87b0775a12c051874a302c9a3

**Comment by fliiiix** [comment]
Cool 👍 fyi: https://luarocks.org/modules/luarocks/luadbi still points to google code!

**Comment by sparked435** [comment]
I'm aware. One thing at a time. :)

Currently gearing up for a release, will fix it all at the same time.
