### ISSUE TITLE
Add ODBC driver

### ISSUE THREAD

**Issue by moteus** [mwild1/luadbi#33]
I write [ODBC driver](https://github.com/moteus/lua-odbc-dbi) for DBI library based on my [Lua-ODBC library](https://github.com/moteus/lua-odbc).
I slitly change tests:
1. I use `select cast(? as <TYPE>) as retval` to [test type encodings](https://github.com/moteus/lua-odbc-dbi/blob/master/spec/test_odbc_spec.lua#L4).
2. I found that ODBC drivers for MySQL/PgSQL does not get any error when call prepare with invalid SQL. So I also [try call execute](https://github.com/moteus/lua-odbc-dbi/blob/master/spec/test_odbc_spec.lua#L60-L62).
3. I do not call test for `returning id` because MySQL does not support it.

For now I add `DBI.lua` to my repo because I want run tests on Travis. But I will not add this to luarocks.
I add it only after you change main luadbi module so it can load ODBC driver. So i can just add luadbi as deps to my module.

**PS.**
 I also add some tests to `fetch`, `close`, `tostring` and execute same statement with different query multiple times

**Comment by sparked435** [comment]
DBI.lua now checks for driver 'ODBC' as dbdodbc as well.

**Comment by moteus** [comment]
Just tested my ODBC driver with v0.6.
 All works.  Add module to luarocks.
