### ISSUE TITLE
How execute prepared query multiple times.

### ISSUE THREAD

**Issue by moteus** [mwild1/luadbi#34]
I can not find describe in doc or test either this should works

```Lua
sth = dbh:prepare("insert into my_table(?)")
sth:execute(1)
sth:execute(2)
```

**Comment by sparked435** [comment]
This should "just work", exactly as shown above.

I have just committed a new test to prove it.

**Comment by moteus** [comment]
but if query return recordset how to close it without fetch all. in my odbc i close cursor in execute if it open
Rhis is just my note. If it not suppose to work i am fine with it

**Comment by mwild1** [comment]
Most database interfaces require you to fetch all the results before executing a new query, so it is best to do that.
