### ISSUE TITLE
Add tag(s) with version numbers

### ISSUE THREAD

**Issue by mp1409** [mwild1/luadbi#36]
Hi there,
we are in the process of pointing the FreeBSD ports collection to this repo as new location for LuaDBI. Currently the LuaDBI version in FreeBSD ports is "0.5". However we noticed that there are no version number tags in this repo.

Of course we could just map some git commit to version 0.5 on our side. But in a couple of months some other distribution might face the same problem. So it would be great if you could tag the appropriate git commit with something like "v0.5". Thanks :-)

References:
- Prosody Issue: https://prosody.im/issues/issue/747
- FreeBSD bug: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212884

**Comment by moteus** [comment]
Checkout #32 
I also wait it for a while :)

**Comment by mwild1** [comment]
Hmm, that's weird and frustrating. I used the migration tool that Google provided. I'll see what I can do (but I'll be away the next few days at least, so I probably won't be able to handle it before next week).

**Comment by moteus** [comment]
@mp1409 I hope you realize that sources on luarocks server do not match to sources in this repo?
So making tags need after do sync. Checkout #32

**Comment by mp1409** [comment]
I understand that it is an undesirable situation that the luarocks version does not match this repo. However, my priority is to fix LuaDBI on FreeBSD. And the FreeBSD LuaDBI port depends on the version 0.5 from the original Google Code repo, which exactly matches commit 58513d50e800f6a4d4e999f9682c747c087eab6f, and not the luarocks version. This means syncing to the luarocks version and tagging that as v0.5 might break the build on FreeBSD again...

Anyway, I can only make suggestions, it is upon the Prosody maintainers (i.e. @mwild1) to decide.

**Comment by fliiiix** [comment]
Is there any chance that we getting that or at least a 0.6 release?

**Comment by sparked435** [comment]
Tagged version 0.5 as specified above.

Additionally, 0.6 is released.

**Comment by fliiiix** [comment]
@sparked435 thank you! I will see if we can update the ports in FreeBSD now.
