### ISSUE TITLE
Make a new release (0.7)

### ISSUE THREAD

**Issue by mwild1** [mwild1/luadbi#48]
Hey folks, I think it's time we made a new release. Anyone feel inclined to take this on? If not, I can do it.

Any objections or blockers that anyone is aware of?

**Comment by sparked435** [comment]
I think a proper resolution to #44 would be good, but that's also a nice to have and not a requirement.

I may be able to find some time to do a formal release this weekend.

**Comment by JorjBauer** [comment]
If anyone is addressing #44, then pull request #46 could fit in that paradigm (as both are initialization problems).

I'm not sure what pull request #45 is waiting for - it adds a bit of Oracle functionality in production environments, and I'd like to see that in a release.

**Comment by kawaii** [comment]
Just giving this a nudge since the current version in Debian 9 repositories has started to cause us some issues on a production server. Seems that at some point a nasty segfault with PostgreSQL databases was fixed and hasn't yet made it into a release in Debian. Would be nice if this could be resolved soon, thanks. :)

**Comment by linuxmaniac** [comment]
@kawaii I already upload a newer version 0.6 to Debian but it's only available in buster/sid
https://tracker.debian.org/pkg/lua-dbi

**Comment by mwild1** [comment]
Given the bug-fixes we already have ready, I have tagged v0.7 in the repository.

If there are some ready PRs, all the more reason for a 0.8 soon :)

**Comment by sparked435** [comment]
0.7 uploaded to Lua Rocks.

Besides the usual notification email to the Lua-L mailing list, anything else that we need/should do for a release? Or is it time to close this?

**Comment by mwild1** [comment]
@sparked435 great, thanks!! Sorry, I missed the version number. Maybe we can tag 0.7.1 with just this fix. I recently had quite some issues debugging a problem with another Lua library and found I wasn't running the version it reported as :) (at least there is no 0.6.1 here).

Maybe we could add a release checklist in a RELEASE.md or something...
