### ISSUE TITLE
Release 0.7.2

### ISSUE THREAD

**Issue by mwild1** [mwild1/luadbi#53]
With multiple important issues fixed since the last release, I think it's time to consider a new one.

This time let's not forget the version number! _(slaps self)_

Anyone object? Any last requests?

**Comment by mwild1** [comment]
Thanks, that's now merged. I'll proceed with tagging 0.7.2 today.

**Comment by dd86k** [comment]
Insert gentle reminder about 0.7.2.

**Comment by sparked435** [comment]
Uploaded 0.7.2 to LuaRocks since it's tagged.
