### ISSUE TITLE
Cannot differentiate NULL and default value with MySQL

### ISSUE THREAD

**Issue by ntki** [mwild1/luadbi#66]
When I execute:
```
dbi = require('DBI')
conn = assert(dbi.Connect("MySQL", "", "user", "", "127.0.0.1", 3306))
user_stmt = assert(conn:prepare("SELECT NULL UNION SELECT 111"))
user_stmt:execute()
print(user_stmt:fetch()[1])
print(user_stmt:fetch()[1])
```
It gives me:
```
0
111
```
Although the correct answer should be:
```
nil
111
```
Or I would like to have some way to check whether a field was NULL.

**Comment by sparked435** [comment]
Thanks for the report and the fix for it; sorry for the long wait to merge. Closing this as it's now in the head branch.
