### ISSUE TITLE
Suggestion: consider making luadbi available as a "luarock"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mwild1/luadbi#9]
```
Please consider making a binary package for Windows available through 
"luarocks".
```

Original issue reported on code.google.com by `theglau...@gmail.com` on 22 Oct 2010 at 4:21

**Comment by moteus** [comment]
Luarocks does not allows specify lua version for rock.
So it does not very useful. Checkout luacom rock wich install binaries for Lua 5.1 
for any Lua version
